export const jobs = [
  {
    id: 1,
    title: 'Frontend Developer',
    location: 'Remote',
    experience: '2+ years',
    type: 'Full-time',
    skills: ['React', 'JavaScript', 'CSS', 'HTML'],
  },
  {
    id: 2,
    title: 'Backend Developer',
    location: 'Onsite - New York',
    experience: '3+ years',
    type: 'Full-time',
    skills: ['Node.js', 'Express', 'MongoDB', 'REST APIs'],
  },
  {
    id: 3,
    title: 'Full Stack Engineer',
    location: 'Remote',
    experience: '4+ years',
    type: 'Full-time',
    skills: ['React', 'Node.js', 'PostgreSQL', 'TypeScript'],
  },
  {
    id: 4,
    title: 'DevOps Engineer',
    location: 'Onsite - San Francisco',
    experience: '3+ years',
    type: 'Contract',
    skills: ['AWS', 'Docker', 'CI/CD', 'Terraform'],
  },
  {
    id: 5,
    title: 'Mobile App Developer',
    location: 'Hybrid - Toronto',
    experience: '2+ years',
    type: 'Part-time',
    skills: ['Flutter', 'React Native', 'iOS', 'Android'],
  },
  {
    id: 6,
    title: 'Software QA Engineer',
    location: 'Remote',
    experience: '1+ years',
    type: 'Full-time',
    skills: ['Cypress', 'Jest', 'Selenium', 'Automation Testing'],
  },
];
